const $=s=>document.querySelector(s);
const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const download=(name,data,type="text/plain")=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
const tools=[
["receipt","🧾","Receipt Maker","Custom receipts with items, quantities, tax, discount, tip, customer data, payment method, status, JSON export and local history."],
["invoice","📄","Invoice Generator","Create invoices from completed jobs with automatic totals and print-to-PDF support."],
["quote","💬","Quote Generator","Create estimates and quotes with line items and automatic calculations."],
["password","🔐","Password Factory","Random passwords, passphrases, PINs, usernames and API-style strings with detailed controls."],
["business-card","💳","Business Card Designer","Build a clean printable card from name, title, company and contact information."],
["keycard","🪪","Keycard Designer","Create front/back access-card mockups with standard card dimensions and printable layouts."],
["percentage","％","Percentage Calculator","Percentage, change, discount, markup and reverse calculations."],
["units","↔","Unit Converter","Length, weight, temperature, storage and time conversions."],
["timesheet","⏱","Timesheet Calculator","Calculate work duration, breaks and total hours."],
["filename","📁","Filename Generator","Generate consistent project filenames from dates, IDs and extensions."],
["random","🎲","Random Generator","Numbers, choices, IDs, hexadecimal strings and test data."],
["colors","🎨","Color / CSS Factory","Generate palettes, gradients, shadows, borders and CSS variables."],
["json","{}","JSON Toolbox","Format, minify, validate and download JSON."],
["csv","▦","CSV Toolbox","Parse CSV into JSON, normalize data and download results."],
["text","T","Text Toolbox","Count, sort, deduplicate and transform text."],
["qr","▣","QR Payload Generator","Create QR-ready payloads and printable encoded text. Optional QR library can be added later."],
["labels","🏷","Label & Tag Studio","Price tags, shelf labels, inventory tags, name tags and shipping-label layouts."],
["files","🗃","File Toolbox","Open local TXT, JSON, CSV, SVG and other browser-readable files."],
["image","🖼","Image Lab","Procedural canvas art and downloadable PNG generation."],
["media","🎙","Media Recorder","Record microphone audio or camera video when the browser grants permission."]
];
const words=["orbit","mango","copper","river","cloud","pixel","forest","rocket","violet","cactus","signal","marble","planet","tunnel","silver","winter","coffee","dragon","paper","sunset","matrix","orange","circuit","meadow","lunar","comet","thunder","maple","kernel","anchor"];
const state={tool:location.hash.slice(1)||"home"};

function shell(){document.body.innerHTML=`<div class="app"><aside class="side"><div class="logo">Utility Forge</div><div class="sub">Local-first browser utilities</div><input id="search" class="search" placeholder="Search tools…"><nav id="nav" class="nav"></nav></aside><main class="main"><div id="view"></div></main></div>`;$("#search").oninput=nav;nav();render()}
function nav(){const q=$("#search").value.toLowerCase();$("#nav").innerHTML=`<button class="${state.tool==="home"?"active":""}" onclick="go('home')">⌂ Home</button>`+tools.filter(t=>(t[2]+" "+t[3]).toLowerCase().includes(q)).map(t=>`<button class="${state.tool===t[0]?"active":""}" onclick="go('${t[0]}')">${t[1]} ${t[2]}</button>`).join("")}
function go(t){state.tool=t;location.hash=t;nav();render()}window.go=go;
function header(t,d){return `<div class="top"><div><div class="eyebrow">Utility Forge</div><div class="title">${esc(t)}</div><div class="muted">${esc(d)}</div></div><div class="row no-print"><button class="btn" onclick="go('home')">All tools</button><button class="btn" onclick="window.print()">Print / PDF</button></div></div>`}
function render(){if(state.tool==="home"){$("#view").innerHTML=header("Utility Forge","A large static toolkit designed for GitHub Pages.")+`<div class="grid">${tools.map(t=>`<article class="card tool" onclick="go('${t[0]}')"><div class="icon">${t[1]}</div><h3>${t[2]}</h3><p>${t[3]}</p><button class="btn">Open</button></article>`).join("")}</div>`;return}const t=tools.find(x=>x[0]===state.tool);$("#view").innerHTML=header(t[2],t[3])+view(state.tool);bind(state.tool)}
function view(id){
if(["receipt","invoice","quote"].includes(id))return docView(id);
if(id==="password")return passwordView();
if(id==="business-card")return cardView();
if(id==="keycard")return keycardView();
if(id==="percentage")return `<div class="card form"><div class="cols"><div class="field"><label>Base</label><input id="pbase" type="number" value="100"></div><div class="field"><label>Percentage</label><input id="prate" type="number" value="15"></div></div><button id="pct" class="btn primary">Calculate</button><div id="pctout" class="output"></div></div>`;
if(id==="units")return unitsView();
if(id==="timesheet")return `<div class="card form"><div class="field"><label>Entries: start | end | break minutes</label><textarea id="entries">09:00 | 17:00 | 30</textarea></div><button id="time" class="btn primary">Calculate</button><div id="timeout" class="output"></div></div>`;
if(id==="filename")return `<div class="card form"><div class="cols"><div class="field"><label>Project</label><input id="project" value="client-project"></div><div class="field"><label>Extension</label><input id="ext" value="pdf"></div></div><button id="fname" class="btn primary">Generate</button><div id="fnameout" class="output"></div></div>`;
if(id==="random")return `<div class="card form"><div class="cols"><div class="field"><label>Count</label><input id="rcount" type="number" value="10"></div><div class="field"><label>Maximum</label><input id="rmax" type="number" value="100"></div></div><button id="random" class="btn primary">Generate</button><div id="randomout" class="output"></div></div>`;
if(id==="colors")return `<div class="card form"><div class="cols"><div class="field"><label>Base hue</label><input id="hue" type="number" value="220" min="0" max="359"></div><div class="field"><label>Count</label><input id="ccount" type="number" value="6" min="2" max="20"></div></div><button id="palette" class="btn primary">Generate</button><div id="colorsout" class="grid"></div></div>`;
if(["json","csv","text"].includes(id))return textView(id);
if(id==="files")return `<div class="card form"><input id="file" type="file"><div id="fileout" class="output"></div><button id="filedownload" class="btn">Download result</button></div>`;
if(id==="image")return `<div class="card form"><div class="cols"><div class="field"><label>Width</label><input id="iw" type="number" value="900"></div><div class="field"><label>Height</label><input id="ih" type="number" value="500"></div></div><button id="draw" class="btn primary">Generate random art</button><canvas id="canvas" class="canvas" width="900" height="500"></canvas><button id="png" class="btn">Download PNG</button></div>`;
if(id==="media")return `<div class="card form media"><div class="row"><button id="audio" class="btn primary">Start audio recording</button><button id="video" class="btn primary">Start video recording</button><button id="stop" class="btn danger">Stop</button></div><video id="preview" controls></video><div id="recout" class="output">Recordings stay in this browser until you download them.</div></div>`;
if(id==="qr")return `<div class="card form"><div class="field"><label>QR payload</label><textarea id="qrtext">https://example.com</textarea></div><button id="qrbtn" class="btn primary">Prepare payload</button><div id="qrout" class="output"></div><p class="muted">This module intentionally avoids sending the payload to a server. A QR renderer can be added as a local library if desired.</p></div>`;
if(id==="labels")return `<div class="card form"><div class="cols"><div class="field"><label>Type</label><select id="ltype"><option>Price Tag</option><option>Shelf Label</option><option>Inventory Tag</option><option>Name Tag</option><option>Shipping Label</option></select></div><div class="field"><label>Text</label><input id="ltext" value="ITEM-001"></div></div><button id="label" class="btn primary">Render</button><div id="labelout" class="preview"></div></div>`;
return `<div class="card"><p>Tool module unavailable.</p></div>`
}
function passwordView(){return `<div class="card form"><div class="cols"><div class="field"><label>Mode</label><select id="pmode"><option>Random</option><option>Passphrase</option><option>PIN</option><option>Username</option><option>API-style</option></select></div><div class="field"><label>Count</label><input id="pcount" type="number" value="5" min="1" max="100"></div><div class="field"><label>Length / words</label><input id="plen" type="number" value="20" min="1" max="256"></div><div class="field"><label>Separator</label><input id="sep" value="-"></div></div><div class="row"><label class="check"><input id="lo" type="checkbox" checked> lowercase</label><label class="check"><input id="up" type="checkbox" checked> uppercase</label><label class="check"><input id="nu" type="checkbox" checked> numbers</label><label class="check"><input id="sy" type="checkbox" checked> symbols</label></div><div class="cols"><div class="field"><label>Custom alphabet</label><input id="alphabet" placeholder="Optional"></div><div class="field"><label>Forbidden characters</label><input id="forbid" placeholder="0OIl"></div></div><div class="row"><button id="genpass" class="btn primary">Generate</button><button id="copypass" class="btn">Copy</button><button id="dlpass" class="btn">Download TXT</button></div><div id="passout" class="output"></div><div id="passstats" class="muted"></div></div>`}
function genPass(){let mode=$("#pmode").value,n=+$("#pcount").value,len=+$("#plen").value,sep=$("#sep").value,chars=($("#lo").checked?"abcdefghijklmnopqrstuvwxyz":"")+($("#up").checked?"ABCDEFGHIJKLMNOPQRSTUVWXYZ":"")+($("#nu").checked?"0123456789":"")+($("#sy").checked?"!@#$%^&*_-+=?":"");if($("#alphabet").value)chars=$("#alphabet").value;chars=[...chars].filter(c=>!$("#forbid").value.includes(c)).join("");const r=()=>crypto.getRandomValues(new Uint32Array(1))[0],out=[];for(let j=0;j<n;j++){if(mode==="Passphrase"){let a=[];for(let i=0;i<len;i++)a.push(words[r()%words.length]);out.push(a.join(sep))}else if(mode==="PIN"){let s="";for(let i=0;i<len;i++)s+=r()%10;out.push(s)}else if(mode==="Username")out.push(words[r()%words.length]+r()%10000);else if(mode==="API-style"){let s="";for(let i=0;i<len;i++)s+="abcdefghijklmnopqrstuvwxyz0123456789"[r()%36];out.push("uf_"+s)}else{let s="";for(let i=0;i<len;i++)s+=chars[r()%Math.max(chars.length,1)]||"A";out.push(s)}}$("#passout").textContent=out.join("\\n");const pool=Math.max(chars.length,1),bits=mode==="Passphrase"?Math.log2(words.length)*len:Math.log2(pool)*len;$("#passstats").textContent=`Estimated entropy: ~${bits.toFixed(1)} bits. Search space is approximately ${pool}^${len} for random-character mode. Generation is local to this browser.`}
function docView(kind){return `<div class="card form"><div class="cols"><div class="field"><label>Business</label><input id="biz" value="Your Business"></div><div class="field"><label>Customer</label><input id="customer" value="Customer Name"></div><div class="field"><label>Document number</label><input id="docno" value="${kind.toUpperCase()}-${Date.now().toString().slice(-6)}"></div><div class="field"><label>Date</label><input id="date" type="date" value="${new Date().toISOString().slice(0,10)}"></div></div><div class="field"><label>Items: description | quantity | unit price</label><textarea id="items">Completed job | 1 | 100</textarea></div><div class="cols"><div class="field"><label>Tax %</label><input id="tax" type="number" value="0"></div><div class="field"><label>Discount</label><input id="discount" type="number" value="0"></div><div class="field"><label>Tip %</label><input id="tip" type="number" value="0"></div><div class="field"><label>Payment method</label><select id="payment"><option>Cash</option><option>Card</option><option>Check</option><option>Bank transfer</option><option>Other</option></select></div></div><div class="row"><button id="updatedoc" class="btn primary">Update</button><button id="docjson" class="btn">Download JSON</button><button id="history" class="btn">Save to history</button></div></div><div id="docpreview" class="preview"></div><div id="dochistory" class="history"></div>`}
function docData(){const items=$("#items").value.split(/\\r?\\n/).map(x=>x.split("|")).filter(x=>x.length>=3).map(x=>({description:x[0].trim(),quantity:+x[1]||0,price:+x[2]||0,total:(+x[1]||0)*(+x[2]||0)})),subtotal=items.reduce((a,x)=>a+x.total,0),discount=+$("#discount").value||0,tax=Math.max(0,subtotal-discount)*(+$("#tax").value||0)/100,tip=(Math.max(0,subtotal-discount)+tax)*(+$("#tip").value||0)/100;return {business:$("#biz").value,customer:$("#customer").value,number:$("#docno").value,date:$("#date").value,payment:$("#payment").value,items,subtotal,discount,tax,tip,total:subtotal-discount+tax+tip}}
function updateDoc(){const d=docData(),kind=state.tool;$("#docpreview").innerHTML=`<section class="paper"><h2>${kind.toUpperCase()}</h2><p><b>${esc(d.business)}</b><br>Customer: ${esc(d.customer)}<br>#${esc(d.number)} · ${esc(d.date)}</p><table><thead><tr><th>Description</th><th>Qty</th><th class="right">Unit</th><th class="right">Total</th></tr></thead><tbody>${d.items.map(x=>`<tr><td>${esc(x.description)}</td><td>${x.quantity}</td><td class="right">$${x.price.toFixed(2)}</td><td class="right">$${x.total.toFixed(2)}</td></tr>`).join("")}</tbody></table><p class="right">Subtotal $${d.subtotal.toFixed(2)}<br>Discount -$${d.discount.toFixed(2)}<br>Tax $${d.tax.toFixed(2)}<br>Tip $${d.tip.toFixed(2)}<br><b>Total $${d.total.toFixed(2)}</b></p><p>Payment: ${esc(d.payment)} · ${kind==="invoice"?"UNPAID":"PAID"}</p><small>Generated locally by Utility Forge.</small></section>`;return d}
function unitsView(){return `<div class="card form"><div class="cols"><div class="field"><label>Value</label><input id="uval" type="number" value="1"></div><div class="field"><label>Conversion</label><select id="uconv"><option value="mi-km">miles → km</option><option value="km-mi">km → miles</option><option value="lb-kg">lb → kg</option><option value="kg-lb">kg → lb</option><option value="ft-m">feet → meters</option><option value="m-ft">meters → feet</option><option value="f-c">°F → °C</option><option value="c-f">°C → °F</option><option value="gb-mb">GB → MB</option><option value="mb-gb">MB → GB</option></select></div></div><button id="unit" class="btn primary">Convert</button><div id="unitout" class="output"></div></div>`}
function textView(id){return `<div class="card form"><div class="field"><label>Input</label><textarea id="textin" placeholder="Paste data here…"></textarea></div><div class="row"><button id="process" class="btn primary">Process</button><button id="textdownload" class="btn">Download</button></div><div id="textout" class="output"></div></div>`}
function cardView(){return `<div class="card form"><div class="cols"><div class="field"><label>Name</label><input id="cn" value="Alex Example"></div><div class="field"><label>Job title</label><input id="ct" value="Developer"></div><div class="field"><label>Company</label><input id="cc" value="Example Co."></div><div class="field"><label>Phone</label><input id="cp" value="555-0100"></div><div class="field"><label>Email</label><input id="ce" value="alex@example.com"></div><div class="field"><label>Website</label><input id="cw" value="example.com"></div></div><button id="card" class="btn primary">Render</button></div><div id="cardout" class="preview"></div>`}
function keycardView(){return `<div class="card form"><div class="cols"><div class="field"><label>Cardholder</label><input id="kn" value="Student Name"></div><div class="field"><label>Organization</label><input id="ko" value="Organization"></div><div class="field"><label>ID</label><input id="ki" value="ID-00001"></div><div class="field"><label>Access level</label><input id="kl" value="Standard"></div></div><button id="key" class="btn primary">Render front / back</button></div><div id="keyout" class="preview"></div>`}
function bind(id){
if(id==="password"){$("#genpass").onclick=genPass;$("#genpass").click();$("#copypass").onclick=()=>navigator.clipboard?.writeText($("#passout").textContent);$("#dlpass").onclick=()=>download("passwords.txt",$("#passout").textContent)}
else if(["receipt","invoice","quote"].includes(id)){updateDoc();$("#updatedoc").onclick=updateDoc;$("#docjson").onclick=()=>download(`${id}.json`,JSON.stringify(docData(),null,2),"application/json");$("#history").onclick=()=>{const a=JSON.parse(localStorage.getItem("uf-history")||"[]");a.unshift({...docData(),type:id,saved:new Date().toISOString()});localStorage.setItem("uf-history",JSON.stringify(a.slice(0,50)));showHistory()};showHistory()}
else if(id==="percentage")$("#pct").onclick=()=>$("#pctout").textContent=((+$("#pbase").value||0)*(+$("#prate").value||0)/100).toFixed(2);
else if(id==="units")$("#unit").onclick=()=>{let v=+$("#uval").value,c=$("#uconv").value,r={"mi-km":v*1.609344,"km-mi":v/1.609344,"lb-kg":v*.45359237,"kg-lb":v/.45359237,"ft-m":v*.3048,"m-ft":v/.3048,"f-c":(v-32)*5/9,"c-f":v*9/5+32,"gb-mb":v*1024,"mb-gb":v/1024}[c];$("#unitout").textContent=r.toFixed(6)};
else if(id==="timesheet")$("#time").onclick=()=>{let total=0;for(const l of $("#entries").value.split("\\n")){const[a,b,br]=l.split("|").map(x=>x?.trim());if(!a||!b)continue;let[ah,am]=a.split(":").map(Number),[bh,bm]=b.split(":").map(Number),m=bh*60+bm-(ah*60+am)-(Number(br)||0);if(m<0)m+=1440;total+=m}$("#timeout").textContent=`${Math.floor(total/60)}h ${total%60}m (${(total/60).toFixed(2)} hours)`};
else if(id==="filename")$("#fname").onclick=()=>$("#fnameout").textContent=`${($("#project").value||"project").replace(/[^a-z0-9_-]+/gi,"-")}_${new Date().toISOString().replace(/[:.]/g,"-")}_${crypto.randomUUID().slice(0,8)}.${$("#ext").value||"txt"}`;
else if(id==="random")$("#random").onclick=()=>$("#randomout").textContent=Array.from({length:+$("#rcount").value||10},()=>Math.floor(Math.random()*(+$("#rmax").value||100))+1).join("\\n");
else if(id==="colors")$("#palette").onclick=()=>{let h=+$("#hue").value,n=+$("#ccount").value;$("#colorsout").innerHTML=Array.from({length:n},(_,i)=>{let c=`hsl(${(h+i*360/n)%360} 70% 58%)`;return `<div class="swatch" style="background:${c}">${c}</div>`}).join("")};
else if(["json","csv","text"].includes(id)){$("#process").onclick=()=>processText(id);$("#textdownload").onclick=()=>download("output.txt",$("#textout").textContent)}
else if(id==="business-card"){const f=()=>$("#cardout").innerHTML=`<div class="bizcard"><div class="muted">${esc($("#cc").value)}</div><div class="big">${esc($("#cn").value)}</div><p>${esc($("#ct").value)}</p><p>${esc($("#cp").value)}<br>${esc($("#ce").value)}<br>${esc($("#cw").value)}</p></div>`;$("#card").onclick=f;f()}
else if(id==="keycard"){const f=()=>$("#keyout").innerHTML=`<div class="grid"><div class="bizcard"><div class="muted">${esc($("#ko").value)}</div><div class="big">${esc($("#kn").value)}</div><p>ID ${esc($("#ki").value)}</p><span class="tag">${esc($("#kl").value)}</span></div><div class="bizcard"><div class="big">ACCESS CARD</div><p>${esc($("#ko").value)}</p><p>Reverse / return instructions</p></div></div>`;$("#key").onclick=f;f()}
else if(id==="files"){$("#file").onchange=async e=>{const f=e.target.files[0];if(!f)return;const text=await f.text();$("#fileout").textContent=text;$("#filedownload").onclick=()=>download("processed-"+f.name,text,f.type||"text/plain")}}
else if(id==="image"){const draw=()=>{const c=$("#canvas"),w=+$("#iw").value||900,h=+$("#ih").value||500;c.width=w;c.height=h;const x=c.getContext("2d");x.fillStyle="#fff";x.fillRect(0,0,w,h);for(let i=0;i<180;i++){x.fillStyle=`hsl(${Math.random()*360} 70% 60%)`;x.beginPath();x.arc(Math.random()*w,Math.random()*h,5+Math.random()*55,0,Math.PI*2);x.fill()}};$("#draw").onclick=draw;$("#png").onclick=()=>download("generated-art.png",$("#canvas").toDataURL().split(",")[1]&&Uint8Array.from(atob($("#canvas").toDataURL().split(",")[1]),c=>c.charCodeAt(0)),"image/png");draw()}
else if(id==="media")mediaBind();
else if(id==="qr")$("#qrbtn").onclick=()=>{$("#qrout").textContent=$("#qrtext").value};
else if(id==="labels")$("#label").onclick=()=>{$("#labelout").innerHTML=`<div class="paper" style="max-width:420px;text-align:center"><div class="muted">${esc($("#ltype").value)}</div><div class="big">${esc($("#ltext").value)}</div><p>PRINT LABEL</p></div>`}
}
function processText(id){let s=$("#textin").value,o="";try{if(id==="json")o=JSON.stringify(JSON.parse(s),null,2);else if(id==="csv")o=JSON.stringify(s.trim().split(/\\r?\\n/).map(r=>r.split(",")),null,2);else{o=s.split(/\\r?\\n/).filter(Boolean);o=[`Lines: ${o.length}`,`Characters: ${s.length}`,`Words: ${(s.trim().match(/\\S+/g)||[]).length}`,"",...o].join("\\n")}}catch(e){o="Error: "+e.message}$("#textout").textContent=o}
function showHistory(){const a=JSON.parse(localStorage.getItem("uf-history")||"[]");$("#dochistory").textContent=a.length?`Saved documents in this browser: ${a.length}`:"No saved documents yet."}
let recorder,parts=[];
async function mediaBind(){$("#audio").onclick=()=>startRec(false);$("#video").onclick=()=>startRec(true);$("#stop").onclick=()=>recorder?.stop()}
async function startRec(video){try{const stream=await navigator.mediaDevices.getUserMedia(video?{audio:true,video:true}:{audio:true});recorder=new MediaRecorder(stream);parts=[];recorder.ondataavailable=e=>e.data.size&&parts.push(e.data);recorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(parts,{type:recorder.mimeType||"audio/webm"});$("#preview").src=URL.createObjectURL(blob);$("#recout").innerHTML=`Recorded ${Math.round(blob.size/1024)} KB · <button class="btn" id="saveRec">Download</button>`;$("#saveRec").onclick=()=>download(video?"recording.webm":"recording.webm",blob,blob.type)};recorder.start();$("#recout").textContent="Recording…"}catch(e){$("#recout").textContent="Recording could not start: "+e.message}}
shell();window.addEventListener("hashchange",()=>{state.tool=location.hash.slice(1)||"home";nav();render()});
