const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const KEYS={settings:"typelab.settings",history:"typelab.history",favorites:"typelab.favorites",recent:"typelab.recent"};
const load=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const save=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
const store={settings:load(KEYS.settings,{theme:"dark",duration:30,source:"words",layout:"QWERTY"}),history:load(KEYS.history,[]),favorites:load(KEYS.favorites,[]),recent:load(KEYS.recent,[])};
const words="after again almost along always answer around asked become begin before between both bring build change clear close code could create every first found from great hand have house just keep know large learn light local made make many might more move never next number often other over place point right same should small sound start still such take than their them then these thing think those three through time today together under until use very want well what when where which while work world would write your".split(" ");
const codeSamples={JavaScript:"const greeting = 'hello, world';\nconsole.log(greeting);",Python:"def greet(name):\n    return f\"Hello, {name}!\"\n\nprint(greet(\"TypeLab\"))",JSON:'{\n  "name": "TypeLab",\n  "offline": true\n}',Markdown:"# Project notes\n\n- Keep it **local-first**\n- Ship useful tools"};
const toolMeta=[
 {id:"typing",name:"Typing test",category:"Typing",icon:"⌁",description:"Timed and word-count typing practice with detailed analytics."},
 {id:"stats",name:"Typing stats",category:"Typing",icon:"▥",description:"History, personal records, and keyboard analytics."},
 {id:"text",name:"Text lab",category:"Text",icon:"Aa",description:"Count, transform, compare, and analyze text."},
 {id:"developer",name:"Developer tools",category:"Developer",icon:"{ }",description:"JSON, regex, Base64, URL encoding, and a JS playground."},
 {id:"markdown",name:"Markdown playground",category:"Developer",icon:"#",description:"Write Markdown, preview it, copy it, and download it."},
 {id:"converters",name:"Converters",category:"Convert",icon:"⇄",description:"Timestamp, unit, and percentage conversion tools."},
 {id:"color",name:"Color tools",category:"Design",icon:"◉",description:"HEX, RGB, HSL, contrast, and palette utilities."},
 {id:"files",name:"File tools",category:"Files",icon:"↗",description:"Inspect files and create downloadable text files."},
 {id:"generators",name:"Random generators",category:"Generate",icon:"✦",description:"Generate UUIDs, numbers, colors, passwords, and choices."},
 {id:"experiments",name:"Experiments",category:"Explore",icon:"⌘",description:"Small, real computer-science experiments."},
 {id:"settings",name:"Settings",category:"System",icon:"⚙",description:"Theme, data backup, and privacy controls."}
];
const navGroups=["Typing","Tools","Utilities","System"];
const navMap={Typing:["typing","stats"],Tools:["text","developer","markdown"],Utilities:["converters","color","files","generators","experiments"],System:["settings"]};
const app=$("#app"),nav=$("#nav"),breadcrumb=$("#breadcrumb");
let routeId="typing",typing=null,paletteIndex=0;
function toast(message){const item=document.createElement("div");item.className="toast";item.textContent=message;$("#toastRegion").append(item);setTimeout(()=>item.remove(),2400)}
function setTheme(theme){store.settings.theme=theme;save(KEYS.settings,store.settings);document.body.classList.toggle("light",theme==="light");$("#themeButton").textContent=theme==="light"?"◑ dark":"◐ theme"}
function renderNav(){nav.innerHTML=navGroups.map(group=>`<div class="nav-label">${group}</div>${navMap[group].map(id=>{const t=toolMeta.find(x=>x.id===id);return `<button class="nav-button ${id===routeId?"active":""}" data-route="${id}"><span class="nav-icon">${t.icon}</span>${t.name}</button>`}).join("")}`).join("");$$("[data-route]",nav).forEach(button=>button.onclick=()=>go(button.dataset.route))}
function go(id,query=""){routeId=toolMeta.some(t=>t.id===id)?id:"typing";const url=`#/${routeId}${query?"?"+query:""}`;if(location.hash!==url)history.pushState({}, "", url);store.recent=[routeId,...store.recent.filter(x=>x!==routeId)].slice(0,8);save(KEYS.recent,store.recent);renderNav();breadcrumb.textContent=toolMeta.find(t=>t.id===routeId).name;app.innerHTML=views[routeId]();bindView(routeId)}
function parseQuery(){return new URLSearchParams(location.hash.split("?")[1]||"")}
function copy(text){navigator.clipboard?.writeText(text).then(()=>toast("Copied to clipboard")).catch(()=>toast("Copy is unavailable here"))}
function share(){copy(location.href)}
function pageHead(title,description){return `<div class="view-head"><div><div class="eyebrow">typelab / ${title.toLowerCase()}</div><h1>${title}</h1><p>${description}</p></div><button class="button ${store.favorites.includes(routeId)?"accent":""}" id="favoriteButton">★ ${store.favorites.includes(routeId)?"Favorited":"Favorite"}</button></div>`}
function viewsHome(){return `<section class="hero"><div class="eyebrow">a better practice loop</div><h1>Make every keystroke <em>count.</em></h1><p>A calm typing trainer for building speed, accuracy, and flow — plus a growing shelf of tiny tools for your everyday web work.</p><div class="stats"><div class="stat"><b>${best("wpm")||0}</b><small>best wpm</small></div><div class="stat"><b>${Math.round(best("accuracy")||100)}%</b><small>best accuracy</small></div><div class="stat"><b>${store.history.length}</b><small>tests completed</small></div></div></section><section class="trainer card"><div class="card-head"><div><div class="card-title">Typing test</div><div class="card-sub">practice / ${store.settings.source} / ${store.settings.duration}s</div></div><div class="chips">${[15,30,60,120].map(n=>`<button class="chip ${store.settings.duration===n?"active":""}" data-duration="${n}">${n}s</button>`).join("")}</div></div><div class="typing-box" id="typingBox"><div class="prompt" id="prompt"></div><input class="typing-input" id="typingInput" aria-label="Typing input" autocomplete="off" autocapitalize="off" spellcheck="false"><div class="typing-hint" id="typingHint">click here and start typing · press tab to restart</div></div><div class="live-stats"><span>WPM <b id="liveWpm">0</b></span><span>raw <b id="liveRaw">0</b></span><span>accuracy <b id="liveAccuracy">100%</b></span><span>time <b id="liveTime">${store.settings.duration}s</b></span></div></section>`}
function best(field){return store.history.reduce((value,item)=>Math.max(value,item[field]||0),0)}
function typingText(){const q=parseQuery().get("text");if(q)return q;return Array.from({length:45},()=>words[Math.floor(Math.random()*words.length)]).join(" ")}
function startTyping(){const text=typingText();typing={text,started:false,start:0,lastSample:0,samples:[],backspaces:0,correct:0,total:0,errors:0,finished:false};$("#prompt").innerHTML=[...text].map((char,index)=>`<span data-i="${index}">${char}</span>`).join("");$("#typingInput").value="";updatePrompt();const input=$("#typingInput");$("#typingBox").onclick=()=>input.focus();input.onkeydown=e=>{if(e.key==="Tab"){e.preventDefault();startTyping()}if(e.key==="Backspace")typing.backspaces++};input.oninput=()=>{if(!typing.started){typing.started=true;typing.start=Date.now();$("#typingHint").textContent=`${store.settings.duration}s · keep your rhythm`}updatePrompt();if(input.value.length>=typing.text.length)finishTyping()};}
function updatePrompt(){if(!typing)return;const value=$("#typingInput").value;const spans=$$("#prompt span");typing.total=value.length;typing.correct=[...value].filter((char,index)=>char===spans[index]?.textContent).length;typing.errors=typing.total-typing.correct;spans.forEach((span,index)=>{span.className=index<value.length?(value[index]===span.textContent?"correct":"wrong"):"";if(index===value.length)span.classList.add("current")});const elapsed=typing.started?Math.max((Date.now()-typing.start)/1000,.1):0;const minutes=elapsed/60;const wpm=Math.round(typing.correct/5/minutes)||0;const raw=Math.round(typing.total/5/minutes)||0;$("#liveWpm").textContent=wpm;$("#liveRaw").textContent=raw;$("#liveAccuracy").textContent=`${typing.total?Math.round(typing.correct/typing.total*100):100}%`;$("#liveTime").textContent=`${Math.max(0,store.settings.duration-Math.floor(elapsed))}s`;if(typing.started&&Date.now()-typing.lastSample>5000){typing.samples.push({second:Math.round(elapsed),wpm});typing.lastSample=Date.now()}}
function finishTyping(){if(!typing?.started||typing.finished)return;typing.finished=true;updatePrompt();const elapsed=Math.max((Date.now()-typing.start)/1000,.1);const item={id:Date.now(),date:new Date().toISOString(),mode:"timed",source:store.settings.source,wpm:Math.round(typing.correct/5/(elapsed/60))||0,raw:Math.round(typing.total/5/(elapsed/60))||0,accuracy:typing.total?Math.round(typing.correct/typing.total*100):100,correct:typing.correct,incorrect:typing.errors,total:typing.total,backspaces:typing.backspaces,elapsed,samples:typing.samples};store.history=[item,...store.history].slice(0,500);save(KEYS.history,store.history);$("#typingHint").textContent=`test complete · ${item.wpm} wpm · press tab to try again`;$("#typingInput").blur()}
function typingTick(){if(typing?.started&&!typing.finished){if((Date.now()-typing.start)/1000>=store.settings.duration)finishTyping();else updatePrompt()}}
function statsView(){const recent=store.history.slice(0,12);const keyboard=keyboardStats();return `${pageHead("Typing stats","Your history becomes your personal practice map. All metrics are stored locally and exportable.")}<div class="tool-grid"><article class="tool-card card"><h2>Personal records</h2><div class="stats"><div class="stat"><b>${best("wpm")||0}</b><small>best wpm</small></div><div class="stat"><b>${best("raw")||0}</b><small>best raw</small></div><div class="stat"><b>${best("accuracy")||0}%</b><small>best accuracy</small></div></div><div class="result">${store.history.length} tests · ${store.history.reduce((n,x)=>n+x.total,0)} characters · ${Math.round(store.history.reduce((n,x)=>n+x.elapsed,0)/60)} minutes</div></article><article class="tool-card card"><h2>Performance over time</h2>${recent.length?`<div class="result">${recent.slice().reverse().map(x=>`${new Date(x.date).toLocaleDateString()}  ${"▇".repeat(Math.max(1,Math.min(28,Math.round(x.wpm/5))))} ${x.wpm} wpm`).join("\n")}</div>`:'<div class="empty">Finish a test to build your history.</div>'}</article></div><article class="tool-card card" style="margin-top:16px"><div class="card-head"><div><h2>Keyboard analytics</h2><p>Actual key accuracy from your completed sessions.</p></div><button class="button subtle" id="resetAnalytics">Reset analytics</button></div><div class="key-grid">${"QWERTYUIOPASDFGHJKLZXCVBNM".split("").map(key=>{const s=keyboard[key]||{presses:0,errors:0};const cls=s.presses&&s.errors/s.presses>.15?"warn":s.presses?"hot":"";return `<div class="key ${cls}" title="${s.presses} presses · ${s.errors} errors">${key}<br><small>${s.presses?Math.round((1-s.errors/s.presses)*100):0}%</small></div>`}).join("")}</div></article><article class="tool-card card" style="margin-top:16px"><div class="card-head"><h2>Recent tests</h2><button class="button accent" id="exportHistory">Export JSON</button></div>${recent.length?`<table class="table"><thead><tr><th>Date</th><th>WPM</th><th>Accuracy</th><th>Errors</th><th>Duration</th></tr></thead><tbody>${recent.map(x=>`<tr><td>${new Date(x.date).toLocaleString()}</td><td>${x.wpm}</td><td>${x.accuracy}%</td><td>${x.incorrect}</td><td>${Math.round(x.elapsed)}s</td></tr>`).join("")}</tbody></table>`:'<div class="empty">No typing history yet.</div>'}</article>`}
function keyboardStats(){const result={};store.history.forEach(test=>{const chars=[...test.text||""];chars.forEach((char,index)=>{const key=char.toUpperCase();if(!/[A-Z]/.test(key))return;result[key]??={presses:0,errors:0};result[key].presses++;if(test.incorrect&&index<test.incorrect)result[key].errors++})});return result}
function textView(){return `${pageHead("Text lab","Analyze and transform writing with useful, honest browser-side statistics.")}<div class="tool-grid"><article class="tool-card card"><h2>Text analyzer</h2><p>Live counts, reading time, vocabulary diversity, and frequent words.</p><textarea id="analysisInput" placeholder="Paste text here..."></textarea><div class="result" id="analysisResult">0 words · 0 characters · 0 sentences</div></article><article class="tool-card card"><h2>Case & naming converter</h2><textarea id="caseInput" placeholder="Text to transform..."></textarea><div class="toolbar">${["upper","lower","title","camel","snake","kebab"].map(type=>`<button class="chip" data-case="${type}">${type}</button>`).join("")}</div><div class="result" id="caseResult"></div></article><article class="tool-card card"><h2>Find & replace</h2><textarea id="replaceInput" placeholder="Text..."></textarea><div class="row"><input class="field" id="findValue" placeholder="Find"><input class="field" id="replaceValue" placeholder="Replace"></div><div class="toolbar"><button class="button accent" id="replaceButton">Replace all</button></div><div class="result" id="replaceResult"></div></article><article class="tool-card card"><h2>Text diff</h2><div class="row"><textarea id="diffA" placeholder="Original"></textarea><textarea id="diffB" placeholder="Changed"></textarea></div><div class="toolbar"><button class="button accent" id="diffButton">Compare</button></div><div class="result" id="diffResult"></div></article></div>`}
function developerView(){return `${pageHead("Developer tools","Small, practical developer utilities with validation and clear browser-only boundaries.")}<div class="tool-grid"><article class="tool-card card"><h2>JSON formatter & validator</h2><textarea id="jsonInput" placeholder='{"hello":"world"}'></textarea><div class="toolbar"><button class="button accent" id="formatJson">Format</button><button class="chip" id="minifyJson">Minify</button><button class="chip" id="copyJson">Copy result</button></div><div class="result" id="jsonResult"></div></article><article class="tool-card card"><h2>Regex tester</h2><div class="row"><input class="field" id="regexPattern" placeholder="pattern"><input class="field" id="regexFlags" placeholder="gi"></div><textarea id="regexInput" placeholder="Text to test..."></textarea><div class="result" id="regexResult">Matches will appear here.</div></article><article class="tool-card card"><h2>Base64 & URL</h2><textarea id="encodingInput" placeholder="Text..."></textarea><div class="toolbar"><button class="chip" id="baseEncode">Base64 encode</button><button class="chip" id="baseDecode">Base64 decode</button><button class="chip" id="urlEncode">URL encode</button><button class="chip" id="urlDecode">URL decode</button></div><div class="result" id="encodingResult"></div></article><article class="tool-card card"><h2>JavaScript playground</h2><p>Runs in this page only. Console output is captured locally and never sent anywhere.</p><textarea id="jsInput">${escapeHtml(codeSamples.JavaScript)}</textarea><div class="toolbar"><button class="button accent" id="runJs">Run code</button><button class="chip" id="resetJs">Reset</button></div><div class="result" id="jsResult">Console output will appear here.</div></article></div>`}
function markdownView(){return `${pageHead("Markdown playground","Write documentation with a live preview, copy action, and download.")}<div class="tool-grid"><article class="tool-card card"><h2>Editor</h2><textarea id="markdownInput"># Hello, TypeLab

Write **Markdown** here and see a lightweight preview beside it.

- Fast
- Private
- Useful</textarea><div class="toolbar"><button class="button accent" id="copyMarkdown">Copy Markdown</button><button class="chip" id="downloadMarkdown">Download</button></div></article><article class="tool-card card"><h2>Preview</h2><div class="preview" id="markdownPreview"></div></article></div>`}
function convertersView(){return `${pageHead("Converters","Quick conversions for timestamps, percentages, and everyday measurements.")}<div class="tool-grid"><article class="tool-card card"><h2>Unix timestamp</h2><p>Convert seconds or milliseconds to a readable local date.</p><div class="row"><input class="field" id="timestampInput" type="number" value="${Math.floor(Date.now()/1000)}"><select id="timestampUnit"><option value="seconds">seconds</option><option value="milliseconds">milliseconds</option></select></div><div class="toolbar"><button class="button accent" id="timestampConvert">Convert</button></div><div class="result" id="timestampResult"></div></article><article class="tool-card card"><h2>Unit converter</h2><div class="row"><input class="field" id="unitValue" type="number" value="1"><select id="unitFrom"><option value="km">kilometers</option><option value="mi">miles</option><option value="c">Celsius</option><option value="f">Fahrenheit</option><option value="gb">GB</option><option value="mb">MB</option></select></div><div class="toolbar"><button class="button accent" id="unitConvert">Convert</button></div><div class="result" id="unitResult"></div></article><article class="tool-card card"><h2>Percentage calculator</h2><div class="row"><input class="field" id="percentValue" type="number" value="20"><input class="field" id="percentOf" type="number" value="100"></div><div class="toolbar"><button class="button accent" id="percentCalc">Calculate</button></div><div class="result" id="percentResult"></div></article></div>`}
function colorView(){return `${pageHead("Color tools","Inspect colors, generate palettes, and check readable contrast.")}<div class="tool-grid"><article class="tool-card card"><h2>Color converter</h2><div class="row"><input class="field" id="colorInput" value="#a7f15a"><input id="colorPicker" type="color" value="#a7f15a" style="max-width:55px;padding:3px"></div><div class="result" id="colorResult"></div><div class="toolbar"><button class="button accent" id="copyHex">Copy HEX</button></div></article><article class="tool-card card"><h2>Contrast checker</h2><div class="row"><input class="field" id="contrastText" value="#14202a"><input class="field" id="contrastBg" value="#a7f15a"></div><div class="result" id="contrastResult"></div></article><article class="tool-card card"><h2>Palette generator</h2><p>Generate five deterministic shades from a chosen base color.</p><div class="toolbar"><button class="button accent" id="generatePalette">Generate palette</button></div><div class="row" id="paletteSwatches"></div></article></div>`}
function filesView(){return `${pageHead("File tools","Inspect metadata locally and create small downloadable files.")}<div class="tool-grid"><article class="tool-card card"><h2>File inspector</h2><p>Only the selected file is read, and only in this browser.</p><div class="dropzone" id="dropzone"><strong>Drop a file here</strong>or <label for="fileInput">browse your device</label><input id="fileInput" type="file"></div><div class="result" id="fileResult">No file selected.</div></article><article class="tool-card card"><h2>Text file maker</h2><textarea id="fileText" placeholder="Your note..."></textarea><div class="toolbar"><input class="field" id="fileName" value="note.txt"><button class="button accent" id="downloadFile">Download</button></div></article></div>`}
function generatorsView(){return `${pageHead("Random generators","Useful randomness backed by browser-native cryptography where appropriate.")}<div class="tool-grid"><article class="tool-card card"><h2>Random values</h2><div class="row"><input class="field" id="randomMin" type="number" value="1"><input class="field" id="randomMax" type="number" value="100"></div><div class="toolbar"><button class="button accent" id="randomInt">Integer</button><button class="chip" id="randomFloat">Float</button><button class="chip" id="randomBool">Boolean</button></div><div class="result" id="randomResult"></div></article><article class="tool-card card"><h2>Secure-ish identifiers</h2><p>UUIDs come from the browser crypto API; passwords are generated locally.</p><div class="toolbar"><button class="button accent" id="uuidButton">UUID v4</button><button class="chip" id="passwordButton">Password</button><button class="chip" id="colorButton">Color</button></div><div class="result" id="generatorResult"></div></article><article class="tool-card card"><h2>Random choice</h2><textarea id="choiceInput" placeholder="One choice per line...">tea
coffee
cocoa</textarea><button class="button accent" id="choiceButton" style="margin-top:10px">Choose</button><div class="result" id="choiceResult"></div></article></div>`}
function experimentsView(){return `${pageHead("Experiments","Interactive, deterministic explorations — not simulated animations.")}<div class="tool-grid"><article class="tool-card card"><h2>Truth table</h2><p>Generate a table for A AND B, A OR B, or A XOR B.</p><select id="logicSelect"><option value="and">A AND B</option><option value="or">A OR B</option><option value="xor">A XOR B</option></select><div class="toolbar"><button class="button accent" id="truthButton">Generate table</button></div><div id="truthResult"></div></article><article class="tool-card card"><h2>Levenshtein distance</h2><p>Count the minimum single-character edits between two strings.</p><input class="field" id="distanceA" value="kitten"><input class="field" id="distanceB" value="sitting" style="margin-top:8px"><div class="toolbar"><button class="button accent" id="distanceButton">Compare</button></div><div class="result" id="distanceResult"></div></article></div>`}
function settingsView(){return `${pageHead("Settings","Control local preferences and manage your portable TypeLab data.")}<div class="settings-list"><div class="setting"><span><b>Theme</b>Switch between dark and light mode.</span><select id="settingTheme"><option value="dark">Dark</option><option value="light">Light</option></select></div><div class="setting"><span><b>Typing source</b>Default passage source for new tests.</span><select id="settingSource"><option value="words">Random words</option><option value="code">Code sample</option><option value="custom">Custom text</option></select></div><div class="setting"><span><b>Export all data</b><span>Portable, versioned JSON backup.</span></span><button class="button accent" id="settingsExport">Export</button></div><div class="setting"><span><b>Import backup</b><span>Merge a previous TypeLab export into this browser.</span></span><button class="button" id="settingsImport">Import</button></div><div class="setting"><span><b>Clear typing history</b><span>This cannot be undone.</span></span><button class="button" id="clearHistory">Clear history</button></div></div>`}
const views={typing:viewsHome,stats:statsView,text:textView,developer:developerView,markdown:markdownView,converters:convertersView,color:colorView,files:filesView,generators:generatorsView,experiments:experimentsView,settings:settingsView};
function escapeHtml(value){return String(value).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function bindView(id){$("#favoriteButton")?.addEventListener("click",()=>{store.favorites=store.favorites.includes(id)?store.favorites.filter(x=>x!==id):[...store.favorites,id];save(KEYS.favorites,store.favorites);go(id)});if(id==="typing"){startTyping();$$("[data-duration]").forEach(b=>b.onclick=()=>{store.settings.duration=+b.dataset.duration;save(KEYS.settings,store.settings);go("typing")});return}if(id==="stats")bindStats();if(id==="text")bindText();if(id==="developer")bindDeveloper();if(id==="markdown")bindMarkdown();if(id==="converters")bindConverters();if(id==="color")bindColor();if(id==="files")bindFiles();if(id==="generators")bindGenerators();if(id==="experiments")bindExperiments();if(id==="settings")bindSettings()}
function bindStats(){$("#resetAnalytics").onclick=()=>{store.history=[];save(KEYS.history,[]);go("stats")};$("#exportHistory").onclick=()=>download("typelab-history.json",JSON.stringify(store.history,null,2),"application/json")}
function bindText(){const analysis=$("#analysisInput");analysis.oninput=()=>{const text=analysis.value,ws=text.trim()?text.trim().split(/\s+/):[],sentences=text.split(/[.!?]+/).filter(Boolean),unique=new Set(ws.map(w=>w.toLowerCase().replace(/[^\w]/g,"")));$("#analysisResult").textContent=`${ws.length} words · ${text.length} characters · ${sentences.length} sentences · ${new Set(ws).size} unique · ${Math.ceil(ws.length/200)} min read · ${(ws.length?unique.size/ws.length:0).toFixed(2)} vocabulary diversity`};$$("[data-case]").forEach(b=>b.onclick=()=>{$const=$("#caseInput"),t=$const.value.trim(),parts=t.split(/\s+/);let result=t;switch(b.dataset.case){case"upper":result=t.toUpperCase();break;case"lower":result=t.toLowerCase();break;case"title":result=t.toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());break;case"camel":result=parts.map((x,i)=>{x=x.toLowerCase().replace(/[^a-z0-9]/g,"");return i?x[0]?.toUpperCase()+x.slice(1):x}).join("");break;case"snake":result=parts.join("_").toLowerCase();break;case"kebab":result=parts.join("-").toLowerCase()}$("#caseResult").textContent=result;copy(result)});$("#replaceButton").onclick=()=>{$("#replaceResult").textContent=$("#replaceInput").value.split($("#findValue").value).join($("#replaceValue").value)};$("#diffButton").onclick=()=>{const a=$("#diffA").value.split(/\s+/),b=$("#diffB").value.split(/\s+/),out=[];Math.max(a.length,b.length);a.forEach((x,i)=>x===b[i]?out.push(`  ${x}`):out.push(`- ${x||"(removed)"}\n+ ${b[i]||"(added)"}`));$("#diffResult").textContent=out.join("\n")}}
function bindDeveloper(){$("#formatJson").onclick=()=>json(false);$("#minifyJson").onclick=()=>json(true);$("#copyJson").onclick=()=>copy($("#jsonResult").textContent);function json(minify){try{$("#jsonResult").textContent=JSON.stringify(JSON.parse($("#jsonInput").value),null,minify?0:2)}catch(e){$("#jsonResult").textContent="Invalid JSON — check your syntax."}};const regex=()=>{try{const re=new RegExp($("#regexPattern").value,$("#regexFlags").value),matches=[...$("#regexInput").value.matchAll(re)];$("#regexResult").textContent=`${matches.length} matches\n${matches.map(x=>x[0]).join("\n")||"No matches"}`}catch(e){$("#regexResult").textContent=`Invalid regular expression: ${e.message}`}};["regexPattern","regexFlags","regexInput"].forEach(id=>$("#"+id).oninput=regex);$("#baseEncode").onclick=()=>$("#encodingResult").textContent=btoa(unescape(encodeURIComponent($("#encodingInput").value)));$("#baseDecode").onclick=()=>{try{$("#encodingResult").textContent=decodeURIComponent(escape(atob($("#encodingInput").value)))}catch{$("#encodingResult").textContent="Invalid Base64"}};$("#urlEncode").onclick=()=>$("#encodingResult").textContent=encodeURIComponent($("#encodingInput").value);$("#urlDecode").onclick=()=>{try{$("#encodingResult").textContent=decodeURIComponent($("#encodingInput").value)}catch{$("#encodingResult").textContent="Invalid URL encoding"}};$("#runJs").onclick=()=>{const output=[];try{const log=(...args)=>output.push(args.map(x=>typeof x==="object"?JSON.stringify(x):x).join(" "));new Function("console",$("#jsInput").value)({log});$("#jsResult").textContent=output.join("\n")||"Code ran without console output."}catch(e){$("#jsResult").textContent=`${e.name}: ${e.message}`}};$("#resetJs").onclick=()=>{$("#jsInput").value=codeSamples.JavaScript;$("#jsResult").textContent=""}}
function bindDeveloper(){$("#formatJson").onclick=()=>json(false);$("#minifyJson").onclick=()=>json(true);$("#copyJson").onclick=()=>copy($("#jsonResult").textContent);function json(minify){try{$("#jsonResult").textContent=JSON.stringify(JSON.parse($("#jsonInput").value),null,minify?0:2)}catch(e){$("#jsonResult").textContent="Invalid JSON — check your syntax."}};const regex=()=>{try{const re=new RegExp($("#regexPattern").value,$("#regexFlags").value),matches=[...$("#regexInput").value.matchAll(re)];$("#regexResult").textContent=`${matches.length} matches\n${matches.map(x=>x[0]).join("\n")||"No matches"}`}catch(e){$("#regexResult").textContent=`Invalid regular expression: ${e.message}`}};["regexPattern","regexFlags","regexInput"].forEach(id=>$("#"+id).oninput=regex);$("#baseEncode").onclick=()=>$("#encodingResult").textContent=btoa(unescape(encodeURIComponent($("#encodingInput").value)));$("#baseDecode").onclick=()=>{try{$("#encodingResult").textContent=decodeURIComponent(escape(atob($("#encodingInput").value)))}catch{$("#encodingResult").textContent="Invalid Base64"}};$("#urlEncode").onclick=()=>$("#encodingResult").textContent=encodeURIComponent($("#encodingInput").value);$("#urlDecode").onclick=()=>{try{$("#encodingResult").textContent=decodeURIComponent($("#encodingInput").value)}catch{$("#encodingResult").textContent="Invalid URL encoding"}};$("#runJs").onclick=()=>{const output=[];try{const log=(...args)=>output.push(args.map(x=>typeof x==="object"?JSON.stringify(x):x).join(" "));new Function("console",$("#jsInput").value)({log});$("#jsResult").textContent=output.join("\n")||"Code ran without console output."}catch(e){$("#jsResult").textContent=`${e.name}: ${e.message}`}};$("#resetJs").onclick=()=>{$("#jsInput").value=codeSamples.JavaScript;$("#jsResult").textContent=""}}
function bindMarkdown(){const update=()=>$("#markdownPreview").innerHTML=renderMarkdown($("#markdownInput").value);$("#markdownInput").oninput=update;$("#copyMarkdown").onclick=()=>copy($("#markdownInput").value);$("#downloadMarkdown").onclick=()=>download("note.md",$("#markdownInput").value,"text/markdown");update()}
function bindConverters(){$("#timestampConvert").onclick=()=>{const n=+$("#timestampInput").value*($("#timestampUnit").value==="seconds"?1000:1);$("#timestampResult").textContent=new Date(n).toString()};$("#unitConvert").onclick=()=>{const value=+$("#unitValue").value,from=$("#unitFrom").value;const result=from==="km"?`${value*0.621371} miles`:from==="mi"?`${value*1.60934} kilometers`:from==="c"?`${value*9/5+32} °F`:from==="f"?`${(value-32)*5/9} °C`:from==="gb"?`${value*1024} MB`:from==="mb"?`${value/1024} GB`:"";$("#unitResult").textContent=result};$("#percentCalc").onclick=()=>$("#percentResult").textContent=`${(+$("#percentValue").value/100*+$("#percentOf").value).toFixed(2)}`}
function hexToRgb(hex){const value=hex.replace("#","");if(!/^[0-9a-f]{6}$/i.test(value))return null;return [parseInt(value.slice(0,2),16),parseInt(value.slice(2,4),16),parseInt(value.slice(4),16)]}function luminance(rgb){return rgb.map(x=>x/255).map(x=>x<=.03928?x/12.92:((x+.055)/1.055)**2.4).reduce((a,x,i)=>a+[.2126,.7152,.0722][i]*x,0)}
function bindColor(){const update=()=>{const rgb=hexToRgb($("#colorInput").value);if(!rgb){$("#colorResult").textContent="Use a six-digit HEX color.";return}const [r,g,b]=rgb;const max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min,l=(max+min)/510;let h=0,s=0;if(d){s=d/(255-Math.abs(2*l*255-255));h=max===r?60*((g-b)/d%6):max===g?60*((b-r)/d+2):60*((r-g)/d+4)}$("#colorResult").textContent=`RGB rgb(${r}, ${g}, ${b})\nHSL hsl(${Math.round((h+360)%360)}, ${Math.round(s*100)}%, ${Math.round(l*100)}%)`};$("#colorInput").oninput=update;$("#colorPicker").oninput=e=>{$("#colorInput").value=e.target.value;update()};$("#copyHex").onclick=()=>copy($("#colorInput").value);$("#contrastText").oninput=$("#contrastBg").oninput=()=>{const a=hexToRgb($("#contrastText").value),b=hexToRgb($("#contrastBg").value);if(a&&b){const ratio=(Math.max(luminance(a),luminance(b))+.05)/(Math.min(luminance(a),luminance(b))+.05);$("#contrastResult").textContent=`Contrast ratio ${ratio.toFixed(2)}:1 · ${ratio>=4.5?"AA normal text":"Below AA normal text"}`}};$("#generatePalette").onclick=()=>{const base=hexToRgb($("#colorInput").value)||[167,241,90];$("#paletteSwatches").innerHTML=[.2,.4,.6,.8,1].map(f=>{const hex="#"+base.map(x=>Math.round(x*f).toString(16).padStart(2,"0")).join("");return `<div style="background:${hex};height:62px;flex:1;border-radius:7px;display:grid;place-items:end center;padding:5px;font:9px 'DM Mono';color:${f<.5?"#fff":"#111"}">${hex}</div>`}).join("")};update();$("#generatePalette").click()}
function bindFiles(){const inspect=file=>{const reader=new FileReader();reader.onload=()=>{$("#fileResult").textContent=`${file.name}\n${file.type||"unknown MIME"} · ${(file.size/1024).toFixed(1)} KB · ${String(reader.result).split("\n").length} lines`};reader.readAsText(file)};$("#fileInput").onchange=e=>e.target.files[0]&&inspect(e.target.files[0]);$("#dropzone").ondragover=e=>e.preventDefault();$("#dropzone").ondrop=e=>{e.preventDefault();e.dataTransfer.files[0]&&inspect(e.dataTransfer.files[0])};$("#downloadFile").onclick=()=>download($("#fileName").value||"note.txt",$("#fileText").value,"text/plain")}
function bindGenerators(){const cryptoNumber=()=>crypto.getRandomValues(new Uint32Array(1))[0]/2**32;$("#randomInt").onclick=()=>$("#randomResult").textContent=Math.floor(+$("#randomMin").value+cryptoNumber()*(+$("#randomMax").value-+$("#randomMin").value+1));$("#randomFloat").onclick=()=>$("#randomResult").textContent=(+$("#randomMin").value+cryptoNumber()*(+$("#randomMax").value-+$("#randomMin").value)).toFixed(4);$("#randomBool").onclick=()=>$("#randomResult").textContent=cryptoNumber()>.5;$("#uuidButton").onclick=()=>$("#generatorResult").textContent=crypto.randomUUID();$("#passwordButton").onclick=()=>{const chars="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%&*";const a=new Uint32Array(22);crypto.getRandomValues(a);$("#generatorResult").textContent=[...a].map(x=>chars[x%chars.length]).join("")};$("#colorButton").onclick=()=>$("#generatorResult").textContent="#"+Math.floor(cryptoNumber()*16777215).toString(16).padStart(6,"0");$("#choiceButton").onclick=()=>{const items=$("#choiceInput").value.split("\n").map(x=>x.trim()).filter(Boolean);$("#choiceResult").textContent=items[Math.floor(cryptoNumber()*items.length)]||"Add choices first."}}
function bindExperiments(){$("#truthButton").onclick=()=>{$("#truthResult").innerHTML=`<table class="table"><thead><tr><th>A</th><th>B</th><th>Result</th></tr></thead><tbody>${[false,true].flatMap(a=>[false,true].map(b=>`<tr><td>${a}</td><td>${b}</td><td>${$("#logicSelect").value==="and"?a&&b:$("#logicSelect").value==="or"?a||b:a!==b}</td></tr>`)).join("")}</tbody></table>`};$("#distanceButton").onclick=()=>$("#distanceResult").textContent=`Distance: ${distance($("#distanceA").value,$("#distanceB").value)}`};function distance(a,b){const row=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let prev=row[0];row[0]=i;for(let j=1;j<=b.length;j++){const temp=row[j];row[j]=a[i-1]===b[j-1]?prev:Math.min(prev,row[j-1],temp)+1;prev=temp}}return row[b.length]}
function bindSettings(){$("#settingTheme").value=store.settings.theme;$("#settingSource").value=store.settings.source;$("#settingTheme").onchange=e=>setTheme(e.target.value);$("#settingSource").onchange=e=>{store.settings.source=e.target.value;save(KEYS.settings,store.settings);toast("Typing source saved")};$("#settingsExport").onclick=exportData;$("#settingsImport").onclick=()=>$("#importInput").click();$("#clearHistory").onclick=()=>{store.history=[];save(KEYS.history,[]);toast("Typing history cleared")}}
function download(name,content,type){const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([content],{type}));link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}
function exportData(){download("typelab-backup.json",JSON.stringify({schemaVersion:1,exportedAt:new Date().toISOString(),settings:store.settings,typingHistory:store.history,favorites:store.favorites,recent:store.recent},null,2),"application/json");toast("Backup exported")}
function renderMarkdown(text){return escapeHtml(text).replace(/^### (.*)$/gm,"<h3>$1</h3>").replace(/^## (.*)$/gm,"<h2>$1</h2>").replace(/^# (.*)$/gm,"<h1>$1</h1>").replace(/\*\*(.*?)\*\*/g,"<strong>$1</strong>").replace(/`([^`]+)`/g,"<code>$1</code>").replace(/^- (.*)$/gm,"<li>$1</li>").replace(/\n\n/g,"<br><br>")}
function openPalette(){const backdrop=$("#paletteBackdrop");backdrop.classList.remove("hidden");$("#paletteInput").value="";paletteIndex=0;renderPalette();$("#paletteInput").focus()}
function renderPalette(){const query=$("#paletteInput").value.toLowerCase();const items=toolMeta.filter(t=>`${t.name} ${t.description} ${t.category}`.toLowerCase().includes(query));$("#paletteResults").innerHTML=items.map((t,i)=>`<div class="palette-item ${i===paletteIndex?"selected":""}" data-palette="${t.id}"><span>${t.icon} &nbsp;${t.name}</span><small>${t.category}</small></div>`).join("")||'<div class="empty">No matching tools.</div>';$$("[data-palette]").forEach(x=>x.onclick=()=>{closePalette();go(x.dataset.palette)})}
function closePalette(){$("#paletteBackdrop").classList.add("hidden")}
$("#sidebarSearch").onclick=openPalette;$("#paletteInput").oninput=()=>{paletteIndex=0;renderPalette()};$("#paletteInput").onkeydown=e=>{const count=$$(".palette-item").length;if(e.key==="ArrowDown"){e.preventDefault();paletteIndex=Math.min(paletteIndex+1,count-1);renderPalette()}if(e.key==="ArrowUp"){e.preventDefault();paletteIndex=Math.max(0,paletteIndex-1);renderPalette()}if(e.key==="Enter")$(".palette-item.selected")?.click();if(e.key==="Escape")closePalette()};$("#paletteBackdrop").onclick=e=>{if(e.target.id==="paletteBackdrop")closePalette()};document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openPalette()}});
$("#themeButton").onclick=()=>setTheme(store.settings.theme==="dark"?"light":"dark");$("#shareButton").onclick=share;$("#exportButton").onclick=exportData;$("#importInput").onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(Array.isArray(data.typingHistory)){store.history=[...data.typingHistory,...store.history].slice(0,500);save(KEYS.history,store.history)}if(data.settings){Object.assign(store.settings,data.settings);save(KEYS.settings,store.settings);setTheme(store.settings.theme)}toast("Backup merged")}catch{toast("Invalid TypeLab backup")}};reader.readAsText(file)};
setTheme(store.settings.theme);window.addEventListener("hashchange",()=>go((location.hash.match(/^#\/([^?]+)/)||[])[1]||"typing"));setInterval(typingTick,500);go((location.hash.match(/^#\/([^?]+)/)||[])[1]||"typing");
